USER_PROFILE = {
    "name": "Lucien Lachaud",
    "target": "AI Engineer / Applied AI Engineer",
    "target_roles": [
        "AI Engineer",
        "Applied AI Engineer",
        "LLM Engineer",
        "RAG Engineer",
        "Data Scientist Junior",
        "Machine Learning Engineer",
        "NLP Engineer",
        "Computer Vision Engineer",
    ],
    "location_preferences": ["Bordeaux", "Paris", "France", "Remote", "Hybrid", "Europe"],
    "strong_skills": [
        "Python",
        "FastAPI",
        "RAG",
        "LLM",
        "FAISS",
        "Vector search",
        "Prompt engineering",
        "Knowledge graphs",
        "Entity extraction",
        "NLP",
        "Computer vision",
        "U-Net",
        "React",
        "Next.js",
        "PostgreSQL",
        "Docker",
        "GitHub Actions",
        "SQLAlchemy",
        "Pydantic",
        "pytest",
        "LangChain",
        "LangGraph",
        "OpenAI",
        "Mistral",
        "Gemini",
    ],
    "experience_keywords": [
        "Thales",
        "knowledge capitalization",
        "multi-source ingestion",
        "LLM orchestration",
        "metadata extraction",
        "audit logging",
        "AI governance",
        "agent governance",
        "policy engine",
        "runtime activity",
        "portfolio project",
    ],
    "weaker_skills_or_to_learn": [
        "AWS",
        "Azure",
        "advanced MLOps",
        "advanced Kubernetes",
        "Spark",
        "Airflow",
        "Terraform",
    ],
    "preferred_contracts": ["CDI", "Junior", "Graduate", "Entry level", "Hybrid", "Remote"],
}
